env:
  - name: AWS_VPC_K8S_CNI_LOGLEVEL
    value: ${cni_loglevel}
  - name: AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG
    value: ${custom_network_cfg}
  - name: ENI_CONFIG_LABEL_DEF
    value: ${eni_config_label}
  - name: AWS_VPC_ENI_MTU
    value: ${eni_mtu}
  - name: AWS_VPC_K8S_CNI_EXTERNALSNAT
    value: ${external_snat}
  - name: AWS_VPC_K8S_CNI_VETHPREFIX
    value: ${veth_prefix}
  - name: AWS_VPC_K8S_PLUGIN_LOG_FILE
    value: ${plugin_log_file}

initContainer:
  image:
    repository: ${initContainer_image.repository}
    tag: ${initContainer_image.tag}
  resources:
    requests:
      memory: ${resources.memory_request}
      cpu: ${resources.cpu_request}
    limits:
      memory: ${resources.memory_limit}
      cpu: ${resources.cpu_limit}

resources:
  requests:
    memory: ${resources.memory_request}
    cpu: ${resources.cpu_request}
  limits:
    memory: ${resources.memory_limit}
    cpu: ${resources.cpu_limit}

warm_ip_target: ${warm_ip_target}
warm_enis_target: ${warm_enis_target}

nodeSelector: {}
affinity: ${jsonencode(affinity)}
tolerations: ${jsonencode(tolerations)}

